enum {
    WEATHER_TYPE_CLEAR,
    WEATHER_TYPE_FEW_CLOUDS,
    WEATHER_TYPE_SCAT_CLOUDS,
    WEATHER_TYPE_BROKEN_CLOUDS,
    WEATHER_TYPE_SHOWER_RAIN,
    WEATHER_TYPE_RAIN,
    WEATHER_TYPE_THUNDER,
    WEATHER_TYPE_SNOW,
    WEATHER_TYPE_MIST
}
